### ISSUE TITLE
[Feature] Change Town Title Requirements

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1282]
### Is your feature request related to a problem? Please describe.

Currently, town titles include Settlement, Hamlet, Village, Town, Large Town, City, Large City, and Metropolis. The requirements for Metropolis aren't much being set at 30 residents. The max amount of town members for a town is 100, so 30 isn't really a, "metropolis."

### Describe the solution you'd like

Set more reasonable requirements for the town titles is the best solution. Below are the requirements for each town title in my own opinion:

**1** | Settlement | Hermit

**4** | Hamlet | Chief

**12** | Village | Baron Von

**20** | Town | Viscount

**28** | Large Town | Count Von

**40** | City | Earl

**48** | Large City | Duke

**60** | Metropolis | Lord

Current requirements are 1, 2, 6,10, 14, 20, 24, 30.

**Comment by shirazmatas** [comment]
Easily fixable in config @FixTheAdmin

**Comment by shirazmatas** [comment]
@KarlOfDuty whenever you got time to go behind fix's back

**Comment by Basically-Andrew** [comment]
This suggestion can be added to EarthMC by adding changing the *numResidents* line of the following lines of code under the levels section of the [config.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) file for Towny. *Note: other lines may be different for earthmc.*

```yml
town_level:
  - numResidents: 0
    debtCapModifier: 1.0
    namePostfix: ' Ruins'
    mayorPrefix: 'Spirit '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 1
    upkeepModifier: 1.0
    townOutpostLimit: 0
  - numResidents: 1
    debtCapModifier: 1.0
    namePostfix: ' (Settlement)'
    mayorPrefix: 'Hermit '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 16
    upkeepModifier: 1.0
    townOutpostLimit: 0
  - numResidents: 4
    debtCapModifier: 1.0
    namePostfix: ' (Hamlet)'
    mayorPrefix: 'Chief '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 32
    upkeepModifier: 1.0
    townOutpostLimit: 1
  - numResidents: 12
    debtCapModifier: 1.0
    namePostfix: ' (Village)'
    mayorPrefix: 'Baron Von '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 96
    upkeepModifier: 1.0
    townOutpostLimit: 1
  - numResidents: 20
    debtCapModifier: 1.0
    namePostfix: ' (Town)'
    mayorPrefix: 'Viscount '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 160
    upkeepModifier: 1.0
    townOutpostLimit: 2
  - numResidents: 28
    debtCapModifier: 1.0
    namePostfix: ' (Large Town)'
    mayorPrefix: 'Count Von '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 224
    upkeepModifier: 1.0
    townOutpostLimit: 2
  - numResidents: 40
    debtCapModifier: 1.0
    namePostfix: ' (City)'
    mayorPrefix: 'Earl '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 320
    upkeepModifier: 1.0
    townOutpostLimit: 3
  - numResidents: 48
    debtCapModifier: 1.0
    namePostfix: ' (Large City)'
    mayorPrefix: 'Duke '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 384
    upkeepModifier: 1.0
    townOutpostLimit: 3
  - numResidents: 60
    debtCapModifier: 1.0
    namePostfix: ' (Metropolis)'
    mayorPrefix: 'Lord '
    townBlockBuyBonusLimit: 0
    namePrefix: ''
    mayorPostfix: ''
    townBlockLimit: 448
    upkeepModifier: 1.0
    townOutpostLimit: 4
```
