### ISSUE TITLE
[BUG] Follow-up on the Shake chance

### ISSUE THREAD

**Issue by Fredeah** [EarthMC/Issue-Tracker#1428]
**https://github.com/EarthMC/Issue-Tracker/issues/1343**

**https://github.com/EarthMC/Issue-Tracker/issues/1361**

In response to the replies on both of the two aforementioned posts about shake having an incorrect success rate and it being a plugin sided error, the fault has now been fixed on mcMMO's end.

Their changelog for version 2.1.203 states the following:
**"Fixed a bug relating to Shake percentages (thanks Lyther)"**

And the post about the fix:
**https://github.com/mcMMO-Dev/mcMMO/pull/4649**

I noticed that the server is currently running an even newer version of the plugin (2.1.204) and thus the plugin sided fault with the lowered shake chance should be fixed. However, the shake chance still shows up as only 15% instead of the standard maxed 56% chance at level 1000 fishing. Therefore I believe that this has now turned into an error on the servers side with 15% being inputted to the config.

Below are the previous shake values before the fault occurred on mcMMO's side, copied from Furballen's post:
0-249: 0%
250-349: 2%
350-499: 6%
500-624: 12%
650-749: 20%
750-849: 30%
850-999: 42%
1000+: 56%

**Comment by Basically-Andrew** [comment]
I believe the previous shake chance values mentioned above can be added by changing shake chance ranks under `ShakeChance:` on line 211. It should look something like this:
```yml
        ShakeChance:
            Rank_1: 0
            Rank_2: 2
            Rank_3: 6
            Rank_4: 12
            Rank_5: 20
            Rank_6: 30
            Rank_7: 42
            Rank_5: 56
```

*Note: I'm presuming the level values for ranks are set as should be*
